export enum SupportedChainId {
  MAINNET = 1,
  GOERLI = 5,
  HARDHAT = 31337,
}

/**
 * https://github.com/LooksRare/contracts-exchange-v1/blob/master/contracts/orderValidation/ValidationCodeConstants.sol
 */
export enum OrderValidatorStatus {
  ORDER_EXPECTED_TO_BE_VALID = "ORDER_EXPECTED_TO_BE_VALID",
  NONCE_EXECUTED_OR_CANCELLED = "NONCE_EXECUTED_OR_CANCELLED",
  NONCE_BELOW_MIN_ORDER_NONCE = "NONCE_BELOW_MIN_ORDER_NONCE",
  ORDER_AMOUNT_CANNOT_BE_ZERO = "ORDER_AMOUNT_CANNOT_BE_ZERO",
  MAKER_SIGNER_IS_NULL_SIGNER = "MAKER_SIGNER_IS_NULL_SIGNER",
  INVALID_S_PARAMETER_EOA = "INVALID_S_PARAMETER_EOA",
  INVALID_V_PARAMETER_EOA = "INVALID_V_PARAMETER_EOA",
  NULL_SIGNER_EOA = "NULL_SIGNER_EOA",
  WRONG_SIGNER_EOA = "WRONG_SIGNER_EOA",
  SIGNATURE_INVALID_EIP1271 = "SIGNATURE_INVALID_EIP1271",
  MISSING_IS_VALID_SIGNATURE_FUNCTION_EIP1271 = "MISSING_IS_VALID_SIGNATURE_FUNCTION_EIP1271",
  CURRENCY_NOT_WHITELISTED = "CURRENCY_NOT_WHITELISTED",
  STRATEGY_NOT_WHITELISTED = "STRATEGY_NOT_WHITELISTED",
  MIN_NET_RATIO_ABOVE_PROTOCOL_FEE = "MIN_NET_RATIO_ABOVE_PROTOCOL_FEE",
  MIN_NET_RATIO_ABOVE_ROYALTY_FEE_REGISTRY_AND_PROTOCOL_FEE = "MIN_NET_RATIO_ABOVE_ROYALTY_FEE_REGISTRY_AND_PROTOCOL_FEE",
  MIN_NET_RATIO_ABOVE_ROYALTY_FEE_ERC2981_AND_PROTOCOL_FEE = "MIN_NET_RATIO_ABOVE_ROYALTY_FEE_ERC2981_AND_PROTOCOL_FEE",
  MISSING_ROYALTY_INFO_FUNCTION_ERC2981 = "MISSING_ROYALTY_INFO_FUNCTION_ERC2981",
  TOO_EARLY_TO_EXECUTE_ORDER = "TOO_EARLY_TO_EXECUTE_ORDER",
  TOO_LATE_TO_EXECUTE_ORDER = "TOO_LATE_TO_EXECUTE_ORDER",
  NO_TRANSFER_MANAGER_AVAILABLE_FOR_COLLECTION = "NO_TRANSFER_MANAGER_AVAILABLE_FOR_COLLECTION",
  CUSTOM_TRANSFER_MANAGER = "CUSTOM_TRANSFER_MANAGER",
  ERC20_BALANCE_INFERIOR_TO_PRICE = "ERC20_BALANCE_INFERIOR_TO_PRICE",
  ERC20_APPROVAL_INFERIOR_TO_PRICE = "ERC20_APPROVAL_INFERIOR_TO_PRICE",
  ERC721_TOKEN_ID_DOES_NOT_EXIST = "ERC721_TOKEN_ID_DOES_NOT_EXIST",
  ERC721_TOKEN_ID_NOT_IN_BALANCE = "ERC721_TOKEN_ID_NOT_IN_BALANCE",
  ERC721_NO_APPROVAL_FOR_ALL_OR_TOKEN_ID = "ERC721_NO_APPROVAL_FOR_ALL_OR_TOKEN_ID",
  ERC1155_BALANCE_OF_DOES_NOT_EXIST = "ERC1155_BALANCE_OF_DOES_NOT_EXIST",
  ERC1155_BALANCE_OF_TOKEN_ID_INFERIOR_TO_AMOUNT = "ERC1155_BALANCE_OF_TOKEN_ID_INFERIOR_TO_AMOUNT",
  ERC1155_IS_APPROVED_FOR_ALL_DOES_NOT_EXIST = "ERC1155_IS_APPROVED_FOR_ALL_DOES_NOT_EXIST",
  ERC1155_NO_APPROVAL_FOR_ALL = "ERC1155_NO_APPROVAL_FOR_ALL",
}
